// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-g9vzA2DuKHO72SD8VJEqGBSxwH418w',
    appId: '1:1060137326685:web:589d517b8990de0023d5b4',
    messagingSenderId: '1060137326685',
    projectId: 'medistock-6b0fa',
    authDomain: 'medistock-6b0fa.firebaseapp.com',
    storageBucket: 'medistock-6b0fa.firebasestorage.app',
    measurementId: 'G-G7VG1XPP8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7LC7BOTs1b96s59sqjBelrLTxlV_ARQ',
    appId: '1:1060137326685:android:ce364f89d5b3f92023d5b4',
    messagingSenderId: '1060137326685',
    projectId: 'medistock-6b0fa',
    storageBucket: 'medistock-6b0fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBXG-l7ScsBE1cST_9owu6GaLVwqAipBs',
    appId: '1:1060137326685:ios:dc6817ce96a6591923d5b4',
    messagingSenderId: '1060137326685',
    projectId: 'medistock-6b0fa',
    storageBucket: 'medistock-6b0fa.firebasestorage.app',
    iosBundleId: 'com.example.medistock',
  );
}
